#!/bin/bash

set -e

if [ -z "$MXEHOME" ]; then
	>&2 echo "\$MXEHOME must be set to the mxe base directory"
	exit 1
fi

cc=x86_64-w64-mingw32.shared-gcc
strp=x86_64-w64-mingw32.shared-strip
pkgconfig=x86_64-w64-mingw32.shared-pkg-config
dll=$MXEHOME/usr/x86_64-w64-mingw32.shared/bin/SDL2.dll

if ! command -v $cc &> /dev/null ; then
	>&2 echo "missing $cc"
	exit 1
fi
if ! command -v $strp &> /dev/null ; then
	>&2 echo "missing $strp"
	exit 1
fi
if ! command -v $pkgconfig &> /dev/null ; then
	>&2 echo "missing $pkgconfig"
	exit 1
fi
if ! command -v zip &> /dev/null ; then
	>&2 echo "missing zip"
	exit 1
fi
if [ ! -f "$dll" ]; then
	>&2 echo "missing $dll"
	exit 1
fi

version=$(git describe --always --dirty)

rm -f gunboat-*.zip
make clean && make CC=$cc PKGCONFIG=$pkgconfig
mkdir -p dist
cp gunboat.exe dist/
cp README.md dist/readme.txt
cp $dll dist/
cp LICENSE dist/license.txt
$strp dist/gunboat.exe
zip -j gunboat-$version.zip dist/*
rm -rf dist
make clean
